In [25]:
import tensorflow as tf


In [26]:
print(tf.__version__) ## version use

1.13.1


In [27]:
## Introduction about tensorflow

In [28]:
## Constants

In [29]:
x1 = tf.constant(1,name='constant_X1')
print(x1)

x2 = tf.constant(2.,name='constant_X2')
print(x2)
 
x3 = tf.constant(3,dtype='float32',name='constant_X3')
print(x3)

Tensor("constant_X1_2:0", shape=(), dtype=int32)
Tensor("constant_X2_2:0", shape=(), dtype=float32)
Tensor("constant_X3_2:0", shape=(), dtype=float32)


In [30]:
v1 = tf.constant([1,2,3],dtype=tf.float32,name='vector_const')
print(v1) # constant vector

Tensor("vector_const_1:0", shape=(3,), dtype=float32)


In [31]:
sess = tf.Session()
sess.run(x1)

1

In [32]:
sess.run(x2)

2.0

In [33]:
sess.run(x3)

3.0

In [34]:
sess.run(v1)

array([1., 2., 3.], dtype=float32)

In [22]:
#create tensor 2D

v2 = tf.constant([
    [1, 2, 3],
    [3, 4, 5]
], dtype=tf.float32, name='2d_matrix')
print(v2)

sess = tf.Session()
sess.run(v2)

# Or use eval

v2.eval(session=sess)

Tensor("2d_matrix_1:0", shape=(2, 3), dtype=float32)


array([[1., 2., 3.],
       [3., 4., 5.]], dtype=float32)

In [23]:
# Perform operator

In [37]:
# Add x1 + x2

# y1 = x1 + x2 ,2 toán tử phải cùng kiểu dtype

y1 = x2 + x3
print(y1)

y1.eval(session=sess)

Tensor("add_4:0", shape=(), dtype=float32)


5.0

In [41]:
v3 = tf.constant([
    [3,2,3],[7,5,6]
],dtype='float',name='2d_matrix_3')

(v3+v2).eval(session=sess)


array([[ 4.,  4.,  6.],
       [10.,  9., 11.]], dtype=float32)